### ISSUE TITLE
Backup last_seen.json

### ISSUE THREAD

**Issue by mathcolo** [transitmatters/new-train-tracker#117]
The NTT working directory now contains `last_seen.json` for the "last seen" times. We should back that up automatically, in case something happens to the server.

**Comment by Joshhw** [comment]
would an S3 bucket work for this?

**Comment by nathan-weinberg** [comment]
Think this is obsolete now with the database removal?

**Comment by nathan-weinberg** [comment]
Nevermind, my head is in the land of architectures past... agreed an S3 bucket is probably the best way to do this - another option might be doing something split where we default to `last_seen.json` but we could leverage the existing DynamoDB for the production deployment (and keep using the `last_seen.json` file so we don't slide back into DB issues stifling local developement)
