### ISSUE TITLE
Database Overhaul

### ISSUE THREAD

**Issue by nathan-weinberg** [transitmatters/new-train-tracker#40]
Should include list of npm commands and things to look out for if setting up a new instance of the project, maybe some troubleshooting tips...

- [x] At the very least modify the README to list a running Postgres server as a dependency
- [ ] Also add some links to helpful, tested OS-specific instructions on how to set one up
- [ ] For our own purposes try to install this from scratch on an EC2/Lightsail Ubuntu instance and write down or script the steps we needed to take
- [ ] Factor any OS-agnostic steps we missed into `create_history_db.py`
- [ ] (Optional) Replace or supplement `secrets.py` with environment variables?
- [x] #84

**Comment by mathcolo** [comment]
The database is gone, so closing this!
