### ISSUE TITLE
Create Ansible playbook specifically for fresh deployments

### ISSUE THREAD

**Issue by nathan-weinberg** [transitmatters/new-train-tracker#41]
The current `deploy-on-lightsail.yml` Ansible playbook can only be used to update existing deployments of the Train Tracker. It wouldn't be a bad idea to have a separate playbook designed for performing fresh deployments of the app.

**Comment by idreyn** [comment]
(Following on from our conversation on Slack) whenever we do this, it should also set up an instance of the history database, by running the following during installation:

```
pipenv run python3 -m server.history.create_history_db
```

and then setting up a crontab entry (using [this module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/cron_module.html)?) to update the database every minute:

```
pipenv run python3 -m server.history.update_history_db
```
