### ISSUE TITLE
Extend Green Line visualization/tracking to account for GLX

### ISSUE THREAD

**Issue by nathan-weinberg** [transitmatters/new-train-tracker#58]
GLX is currently planned to open in December for the Union Branch and May for the Medford Branch. We need to extend the GL code to take into account these new stations. @idreyn If you have any details as to what exactly needs to be done feel free to drop them here for whoever ends up picking this up.

**Comment by idreyn** [comment]
The bulk of this task is likely to be making changes to [`lines.js`](https://github.com/transitmatters/new-train-tracker/blob/master/src/lines.js), which defines the shapes and stations for each line.

- Science Park and Lechmere should be restored to `glSharedStations`
- `greenShared` needs to be refactored to account for the fact that the D and E lines will no longer start within the trunk (and will need their own `start()` commands)
- `greenDShape` and `greenEShape` should each get some new path drawing commands, probably a `start`, a `stationRange` with a nested `line`, and then a `wiggle` to join up with the trunk. 

We might want to put some thought into how the Medford branch appears while it's still under construction. We could easily make it semitransparent, or with a little more work make it a dashed line.

Also: we need to hard-code the IDs of new stations into this file, and the code expects to cross-reference those with what it gets from the server. We could hack some test data into `initial_request_data` on the server for the purposes of this task, but eventually we'll need to go back and update this when the real IDs start to appear in GTFS.

**Comment by devinmatte** [comment]
👋 I have been playing around with contributing to this issue through #79. Happy to take any and all feedback from the maintainers. Union square should be opening within a month so figured I would take a crack at it now
