### ISSUE TITLE
Add history and statistics page

### ISSUE THREAD

**Issue by nathan-weinberg** [transitmatters/new-train-tracker#59]
Similar to what is being done on [newtrains.today](https://newtrains.today/) and more also
@mathcolo If you have any details as to what exactly needs to be done feel free to drop them here for whoever ends up picking this up.

**Comment by mathcolo** [comment]
Two parts to this
a) Modify server to reply with old train info (either counts or the full set of labels, whatever?) — probably [here](https://github.com/transitmatters/new-train-tracker/blob/62a780181426ef05f0a460621f14ac1bf031c672/server/mbta_api.py#L78)
b) Throw it on the frontend somewhere—ask the team and/or @idreyn for input. The [frontend request](https://github.com/transitmatters/new-train-tracker/blob/master/src/useMbtaApi.js#L51) will need to be modified, and then displayed somewhere on the page.

**Comment by austinjpaul** [comment]
Brainstorming: 
new train trips per day over time would be nice (also, as a percentage of total trips, if that's possible?)
number of distinct cars seen (again over time) would be nice also to track rollout. 
I think i stole both of these ideas from @friendchris, who might also have more thoughts

**Comment by idreyn** [comment]
Just wanted to leave my own take on this feature. I changed the name of the card to emphasize that there's two different kinds of data that we want to compute and display here.

## Real-time statistics about the state of the line

- When a new train was last seen
- Total number of new trains running
- Total number of _any_ trains running
- Total number of new train cars delivered for each line (may have to be updated by hand)
- Total number of expected cars delivered for each line (may have to be updated by hand)

This is data that we can compute with MBTA API data that's already on hand, and we can basically display it as two fractions.

## Historical data about the line

  - Number of runs/service hours of new trains per day over time (2018-present)
  - Number of new train cars delivered, over time (2018-present)

This is data we'll need to aggregate — the working plan is to do it here: https://github.com/transitmatters/t-performance-dash/pull/165. Assuming that we have a way to load that into the NTT, we would then want to use a charting library to draw some time-series graphs of this information. We've had great results using [chartjs](https://www.chartjs.org/) in the [performance dashboard](https://github.com/transitmatters/t-performance-dash) and the [recovery dashboard](https://github.com/transitmatters/mbta-covid-recovery-dash/), and both repos have some good example usages.

## Where do we show this?

Two possibilities: either show per-line statistics on each line's tab, or add a new History/Stats tab to the selector bar on top. A separate stats tab has two big benefits:

- Easier discoverability — no need to scroll past real-time line info to find
- Aggregation of all data in one place.

I also see two minor downsides:

- Adding a fourth tab to the GL/OL/RL selector's current design will be a bit of a squeeze on small phones
- It's not clear to me what color scheme it should use

If I were building this, I'd first consider adding the stats/history data to each line's tab, underneath the strip map. I would use [CSS scroll snap](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap) and a thin white divider line to visually separate this screen from the map. The green/orange/red tab background colors should work nicely if we do the stats text and charts in all-white, perhaps with some varying opacity.

For discoverability's sake, I'd also add a subtle `position: fixed` notice when the strip map is shown that somehow indicates "scroll down to see history". The big upside to doing it this way is that when there are no new trains running on a line, the history screen will naturally appear on its tab, which is a big improvement from the bare "last seen" notice we have.

I don't actually know if this would work _well_, but it's what I would try, and I wanted to clarify what I'm talking about when proposing an alternative to a new stats tab. And for what it's worth, I think we could probably put history data below the maps _and_ in a new tab if we design the UI well.

**Comment by thiteixeira** [comment]
Started a WIP [here](https://github.com/transitmatters/new-train-tracker/pull/99)
