### ISSUE TITLE
Add footer with dynamic version tags

### ISSUE THREAD

**Issue by nathan-weinberg** [transitmatters/new-train-tracker#60]
The NTT currently lacks a footer - we should add one similar to the DD with links and a dynamic version tag

**Comment by nathan-weinberg** [comment]
@idreyn I'm happy to take a stab at this - could you provide some guidance as to how I can add a footer section in React?

**Comment by idreyn** [comment]
You'll want to render something like a `<div className="footer">` under the `<Line>` component in `App.js`, and then you can style that with a `.footer {}` in `main.css`. If we're just putting the version information there I would play with using:

```css
.footer {
    position: fixed;
    top: 0;
    bottom: 0;
}
```

so it sticks in the corner without altering the layout or size of the page.
