### ISSUE TITLE
Add labels for GL branch stations

### ISSUE THREAD

**Issue by idreyn** [transitmatters/new-train-tracker#61]
Mobile viewports are too small to fit full station names but we could:

- Make them teeny tiny
- Abbreviate them
- Make them appear when the station dot is tapped

<img src="https://user-images.githubusercontent.com/2208769/121274910-82815e80-c899-11eb-8743-20e306ff199c.png" height="500"/>

**Comment by nathan-weinberg** [comment]
Perhaps use these https://github.com/transitmatters/slow-zones/blob/main/stop_abbreviations.json
