### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by nathan-weinberg** [transitmatters/new-train-tracker#94]
Similar to how we've done this for other TM projects

**Comment by nathan-weinberg** [comment]
Some CD changes will be required with this

**Comment by thiteixeira** [comment]
From a Github side of things is quite [easy](https://github.com/github/renaming#renaming-existing-branches) (but it has to be someone with permission to change the repo).

**Comment by thiteixeira** [comment]
From a Github side of things is quite [easy](https://github.com/github/renaming#renaming-existing-branches) (but it has to be someone with permission to change the repo).

**Comment by nathan-weinberg** [comment]
Ensure changes from https://github.com/transitmatters/new-train-tracker/pull/122 are incorporated as part of this.

**Comment by devinmatte** [comment]
We should do this soon, NTT has slowed down in feature work as of late, it would be a good time

**Comment by nathan-weinberg** [comment]
Done
